---
- name: Ensure epel repository package is present
  tags:
    - epel
  become: true
  ansible.builtin.dnf:
    name: epel-release
    state: present
    update_cache: true

- name: Ensure epel repository dependencies are enabled
  tags:
    - epel
  become: true
  community.general.dnf_config_manager:
    name: powertools
    state: enabled
  when:
    - ansible_distribution_major_version == '8'

- name: Ensure epel repository dependencies are enabled
  tags:
    - epel
  become: true
  community.general.dnf_config_manager:
    name: crb
    state: enabled
  when:
    - ansible_distribution_major_version >= '9'

- name: Ensure epel repositories are managed
  tags:
    - epel
  become: true
  community.general.dnf_config_manager:
    name: "{{ _epel.name }}"
    state: "{{ _epel.state }}"
  loop: "{{ epel_repositories }}"
  loop_control:
    label: "{{ _epel.name | d(none) }}"
    loop_var: _epel
  when:
    - _epel.name is defined
    - _epel.state is defined

- name: Ensure epel repository gpg key is present
  tags:
    - epel
  become: true
  ansible.builtin.rpm_key:
    key: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    state: present

- name: Ensure epel repository packages are present
  tags:
    - epel
  become: true
  ansible.builtin.dnf:
    name: "{{ epel_packages }}"
    state: present
    update_cache: true
...
