---
dependencies: []
galaxy_info:
  role_name: dnf
  author: Taylor Kimball
  description: Dandified Yum
  license: GPLv3
  min_ansible_version: 2.15.0
  platforms:
    - name: EL
      versions:
        - '8'
        - '9'
  galaxy_tags:
    - dnf
    - linux
...
