---
- name: Ensure procps package is installed
  tags:
    - sysctl
  become: true
  ansible.builtin.apt:
    name: procps
    state: present
    update_cache: true
  when:
    - ansible_os_family == 'Debian'

- name: Ensure procps-ng package is installed
  tags:
    - sysctl
  become: true
  ansible.builtin.dnf:
    name: procps-ng
    state: present
    update_cache: true
  when:
    - ansible_os_family == 'RedHat'

- name: Ensure sysctl.conf configuration is managed
  tags:
    - sysctl
  become: true
  ansible.builtin.template:
    dest: /etc/sysctl.conf
    group: root
    mode: '0644'
    owner: root
    src: sysctl.conf.j2
  notify:
    - Reload sysctl
  when:
    - sysctl_conf | length > 0

- name: Ensure sysctl.d configurations are managed
  tags:
    - sysctl
  become: true
  ansible.builtin.template:
    dest: "/etc/sysctl.d/{{ _sysctl.name }}.conf"
    group: root
    mode: '0644'
    owner: root
    src: sysctl_d.j2
  notify:
    - Reload sysctl
  loop: "{{ sysctl_d }}"
  loop_control:
    label: "{{ _sysctl.name | d(none) }}"
    loop_var: _sysctl
  when:
    - sysctl_d | length > 0
    - _sysctl.name is defined
    - _sysctl.parameters is defined
    - _sysctl.parameters | length > 0
...
