---
- name: Verify
  hosts: all
  pre_tasks:
    - name: Ensure group information is gathered
      tags:
        - group
      ansible.builtin.getent:
        database: group
        fail_key: false

    - name: Ensure groups are in expected state
      tags:
        - group
      ansible.builtin.assert:
        that:
          - "'johndoe' in getent_group"
          - "'janedoe' in getent_group"
          - getent_group.johndoe.1 == '1001'
          - getent_group.janedoe.1 == '1002'

    - name: Ensure inventory lists are formatted
      tags:
        - group
      ansible.builtin.set_fact:
        group_list:
          "{{ group_list |
              map('combine', {'state': 'absent'}) }}"

  roles:
    - group
...
