---
- name: Ensure test play is executed
  hosts: all
  roles:
    - role: chrony
      chrony_conf:
        - authselectmode require
        - cmdport 0
        - driftfile /var/lib/chrony/drift
        - hwtimestamp *
        - log measurements statistics tracking
        - logdir /var/log/chrony
        - makestep 1.0 3
        - minsources 2
        - ntsdumpdir /var/lib/chrony
        - rtcsync
        - server ntppool1.time.nl iburst nts
        - server ntppool2.time.nl iburst nts
        - sourcedir /run/chrony-dhcp
      chrony_options:
        - '-F 1'
...
