---
- name: Ensure test play is verified
  hosts: all
  tasks:
    - name: Ensure timedatectl status is gathered
      tags:
        - timedatectl
      become: true
      ansible.builtin.command:
        cmd: >
          timedatectl show
      register: __timedatectl_show
      changed_when: false

    - name: Esnure timedatectl configuration matches
      tags:
        - timedatectl
      ansible.builtin.assert:
        that:
          - "'LocalRTC=no' in __timedatectl_show.stdout"
          - "'NTP=no' in __timedatectl_show.stdout"
          - "'Timezone=UTC' in __timedatectl_show.stdout"
...
