---
dependencies: []
galaxy_info:
  role_name: cronie
  author: Taylor Kimball
  description: Cron daemon for executing programs at set times
  license: GPLv3
  min_ansible_version: 2.15.0
  platforms:
    - name: EL
      versions:
        - all
  galaxy_tags:
    - crond
    - cronie
    - linux
...
