---
- name: Converge
  hosts: all
  roles:
    - role: rush
      rush_global:
        - debug 1
        - include-security all
        - sleep-time 0
      rush_rules:
        - name: default
          rules:
            - clrenv
            - keepenv USER LOGNAME HOME PATH
            - fall-through
        - name: rsync
          rules:
            - chdir "~"
            - match $command ~ "^rsync --server"
            - set program = "/usr/bin/rsync"
            - set [0] = "/usr/bin/rsync"
...
